# Generated by Django 4.0.4 on 2022-06-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_author_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
