# Generated by Django 4.0.4 on 2022-06-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_book_book_author_delete_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_available',
            field=models.IntegerField(null=True),
        ),
    ]
