# Generated by Django 4.0.4 on 2022-06-24 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_book_book_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-book_creation']},
        ),
        migrations.AddField(
            model_name='book',
            name='book_creation',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
